import{FLORA as f}from"../js/skins/vivo.js?v=f31c179";import{FAUNA_DEF as v}from"../sim/fauna.js?v=f31c179";import{floraDe as h}from"../sim/escenarios.js?v=f31c179";import{CASTAS as x,HORMIGAS as A,radioHormiga as w}from"./recursos-grafico.js?v=f31c179";const z={roble:{es:"Roble",en:"Oak"},olivo:{es:"Olivo",en:"Olive"},tilo:{es:"Tilo",en:"Lime"},albaricoquero:{es:"Albaricoquero",en:"Apricot"},pradera:{es:"Mata de pradera",en:"Meadow tuft"},zarzal:{es:"Zarzal",en:"Bramble"},frambueso:{es:"Frambueso",en:"Raspberry"},pino:{es:"Pino",en:"Pine"},palmera:{es:"Palmera",en:"Palm"},acacia:{es:"Acacia",en:"Acacia"},eucalipto:{es:"Eucalipto",en:"Eucalyptus"}},y=Object.freeze(Object.fromEntries([...v.especies.map(e=>[e.tipo,e.col]),["marabunta",v.marabunta.col]])),F=(e,r)=>e&&(e[r]??e.es)||"";function D(e){const r=h(e);return r?Object.entries(r).filter(([o,a])=>a>0&&f.some(i=>i.nombre===o)).sort((o,a)=>a[1]-o[1]||o[0].localeCompare(a[0])).map(([o])=>o):[]}function j(e){if(typeof e!="string")return null;const[r,o]=e.split("/");if(r==="especies"){const a=A.find(t=>t.clave===o);return a?{clase:"hormiga",piezas:x.filter(t=>t.id!=="guerrera"||a.conGuerrera).map(t=>({id:t.id,nombre:t.nombre,receta:{tipo:"hormiga",morfo:a.clave,r:w(a,t,1),reina:t.id==="reina"}}))}:null}if(r==="fauna"){const a=y[o];return a==null?null:{clase:"bicho",piezas:[{id:o,nombre:null,receta:{tipo:"bicho",e:a}}]}}if(r==="mundo"){const a=D(o);return a.length?{clase:"planta",sitio:o,piezas:a.map(i=>{const t=f.findIndex(s=>s.nombre===i);return{id:i,nombre:z[i]||{es:i,en:i},receta:{tipo:"planta",planta:i,esp:t,arbol:f[t].porte==="arbol"}}})}:null}return null}const E={es:{titulo:"El modelo en 3D",pie:"El mismo modelo que se dibuja en la partida, sin el recorte de la c\xE1mara t\xE1ctica.",ver:"Ver en 3D",cargando:"Cargando el visor\u2026",reposo:"El visor 3D se carga al pedirlo.",sinWebgl:"Este navegador no puede dibujar en 3D; la ficha se queda con su dibujo de siempre.",lienzo:"Modelo tridimensional. Arrastra para girar; con el lienzo enfocado, flechas y teclas + / \u2212.",piezas:"Qu\xE9 modelo se ense\xF1a",centrar:"Ver completo"},en:{titulo:"The 3D model",pie:"The very model drawn in a match, without the tactical camera cutting it off.",ver:"View in 3D",cargando:"Loading the viewer\u2026",reposo:"The 3D viewer loads on request.",sinWebgl:"This browser cannot draw in 3D; the card keeps its usual artwork.",lienzo:"Three-dimensional model. Drag to turn; with the canvas focused, arrows and + / \u2212 keys.",piezas:"Which model is shown",centrar:"Fit in view"}},O=`
.guia-3d { margin-top: var(--g-5, 24px); padding-top: var(--g-4, 16px); border-top: 1px solid var(--g-borde, #3b352d); }
.guia-3d h4 { margin: 0 0 var(--g-1, 4px); font-size: .95rem; }
.guia-3d-pie { margin: 0 0 var(--g-3, 12px); color: var(--g-tenue, #b7ac9a); font-size: .82rem; }
.guia-3d-caja { position: relative; height: 280px; border: 1px solid var(--g-borde, #3b352d);
  border-radius: var(--g-radio, 6px); background: #2a2b26; overflow: hidden; }
.guia-3d-caja > canvas { display: block; width: 100%; height: 100%; touch-action: none; cursor: grab; }
.guia-3d-caja > canvas:focus-visible { outline: 3px solid var(--g-acento, #78a7ef); outline-offset: -3px; }
.guia-3d-estado { position: absolute; inset: 0; margin: 0; display: flex; align-items: center; justify-content: center;
  padding: var(--g-3, 12px); text-align: center; color: var(--g-tenue, #b7ac9a); font-size: .82rem; }
.guia-3d-estado[hidden] { display: none; }
.guia-3d-mandos { display: flex; flex-wrap: wrap; gap: var(--g-2, 8px); margin-top: var(--g-3, 12px); }
.guia-3d-mandos button[aria-pressed="true"] { border-color: var(--g-acento, #78a7ef); color: var(--g-acento-vivo, #a9c8f6); }
.guia-3d-dato { margin: var(--g-2, 8px) 0 0; color: var(--g-tenue, #b7ac9a); font-size: .75rem;
  font-variant-numeric: tabular-nums; min-height: 16px; }
@media (max-width: 520px) { .guia-3d-caja { height: 220px; } }
`;function C(){if(typeof document>"u"||document.getElementById("guia-3d-estilos"))return;const e=document.createElement("style");e.id="guia-3d-estilos",e.textContent=O,document.head.append(e)}const n=(e,r,o)=>{const a=document.createElement(e);return r&&(a.className=r),o!=null&&(a.textContent=o),a},T=(e,r="")=>{const o=n("button",r,e);return o.type="button",o};let u=null;function I(e,r,o="es"){const a=j(r&&r.id);if(!a||!e||typeof document>"u")return!1;C();const i=o==="en"?"en":"es",t=E[i],s=n("section","guia-3d");s.setAttribute("aria-label",t.titulo),s.append(n("h4","",t.titulo),n("p","guia-3d-pie",t.pie));const p=n("div","guia-3d-caja"),d=n("p","guia-3d-estado",t.reposo);d.setAttribute("role","status"),p.append(d);const c=n("div","guia-3d-mandos");c.setAttribute("role","group"),c.setAttribute("aria-label",t.piezas);const m=n("p","guia-3d-dato");m.setAttribute("aria-live","polite");const l=T(t.ver);l.setAttribute("aria-label",`${t.ver}: ${r.titulo}`),c.append(l),s.append(p,c,m),e.append(s);const b=()=>{l.disabled=!0,d.textContent=t.cargando,(u||(u=import("./visor3d.js?v=f31c179"))).then(({montarVisor:g})=>g({caja:p,estado:d,mandos:c,dato:m,receta:a,idioma:i,tx:t,abrir:l})).catch(g=>{u=null,l.disabled=!1,d.textContent=t.sinWebgl,console.error(g)})};return l.addEventListener("click",b),u&&b(),!0}export{j as modelosDe,I as pintarModelos3D};
